spring.application.name=crowdfunding
server.port=8081
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
spring.datasource.url=${DB_URL:}
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET:default-secret-change-in-production}
jwt.expiration=86400000